In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
df.total_bedrooms

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [4]:
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')

c:\Users\Kacha\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
df1 = dataset['train'].to_pandas()

In [6]:
df1[['job_title_short' , 'job_title']].iloc[90:100]

         job_title_short                                          job_title
90        Data Scientist                                     Data Scientist
91        Data Scientist                                     Data Scientist
92         Data Engineer            Remote - Data Engineer - Permanent - W2
93          Data Analyst       IT Finance / TBM Data Analyst - Remote | WFH
94         Data Engineer                   Data Engineer - Cloud Operations
95         Data Engineer                                      Data Engineer
96         Data Engineer                                      Data Engineer
97          Data Analyst  Systems & Data Analyst - Exploitation, Missing...
98  Senior Data Engineer                         Senior Data Engineer (AWS)
99         Data Engineer  Senior/Staff Data Engineer – Apache Spark (Jav...

In [7]:
df1.iloc[90:100 , 0:2]

         job_title_short                                          job_title
90        Data Scientist                                     Data Scientist
91        Data Scientist                                     Data Scientist
92         Data Engineer            Remote - Data Engineer - Permanent - W2
93          Data Analyst       IT Finance / TBM Data Analyst - Remote | WFH
94         Data Engineer                   Data Engineer - Cloud Operations
95         Data Engineer                                      Data Engineer
96         Data Engineer                                      Data Engineer
97          Data Analyst  Systems & Data Analyst - Exploitation, Missing...
98  Senior Data Engineer                         Senior Data Engineer (AWS)
99         Data Engineer  Senior/Staff Data Engineer – Apache Spark (Jav...

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [9]:
df1[(df1.job_title_short == 'Data Analyst') & (df1.salary_year_avg.notna())]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
180,Data Analyst,Data Analyst III,"Dos Palos, CA",via My ArkLaMiss Jobs,Full-time,False,"California, United States",2023-02-27 13:00:39,False,True,United States,year,90250.0,NaN,California Health & Wellness,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}"
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
988,Data Analyst,DATA ANALYST (ONSITE),"Springfield, MA",via Indeed,Full-time,False,"New York, United States",2023-11-21 13:00:13,False,False,United States,year,62623.0,NaN,Springfield Public Schools,"['sql', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr..."
1413,Data Analyst,Junior BI Developer,"Atlanta, GA",via Ai-Jobs.net,Full-time,False,Georgia,2023-10-31 13:57:41,False,True,United States,year,71300.0,NaN,Guidehouse,"['sql', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
784423,Data Analyst,Sales Data Analyst,"Juriquilla, Qro., Mexico",via Ai-Jobs.net,Full-time,False,Mexico,2023-01-05 06:43:20,False,False,Mexico,year,80850.0,NaN,Charger Logistics Inc,"['tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi']}"
784882,Data Analyst,Merchandising Analyst (Data Analyst),"Denton, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 15:29:24,False,False,United States,year,87500.0,NaN,Insight Global,"['sql', 'vba', 'tableau', 'excel', 'alteryx']","{'analyst_tools': ['tableau', 'excel', 'altery..."
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [16]:
df1['job_posted_date']= pd.to_datetime(df1.job_posted_date)

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [19]:
df1['job_posted_month'] = df1.job_posted_date.dt.month

In [22]:
df1.sort_values('job_posted_date' , inplace=True)

In [24]:
df1.drop(labels='salary_hour_avg' , axis=1 , inplace=True)

In [26]:
df1.dropna(subset=['salary_year_avg'] , inplace=True)

In [27]:
df1

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month
108883,Data Scientist,Data Scientist,"Calabasas, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:02:56,False,True,United States,year,110000.0,PlanetArt,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr...",1
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01 00:06:13,True,False,Argentina,year,65000.0,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",1
365786,Business Analyst,Hospitality Operations Analyst,Anywhere,via Goodwin Recruiting | Job Board,Full-time,True,Georgia,2023-01-01 00:17:55,False,True,United States,year,90000.0,Goodwin Recruiting,"['sql', 'excel', 'powerpoint', 'outlook']","{'analyst_tools': ['excel', 'powerpoint', 'out...",1
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01 00:17:58,False,False,United States,year,55000.0,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea...",1
108099,Data Scientist,Lead Data Scientist (Hybrid),"Burnsville, MN",via Recruit.net,Full-time,False,"Illinois, United States",2023-01-01 00:21:09,False,False,United States,year,120531.0,Apple Valley,"['java', 'sql', 'sql server', 'spring']","{'databases': ['sql server'], 'libraries': ['s...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186163,Senior Data Scientist,"Tech Lead / Sr Data Scientist, Product Analyti...","Los Angeles, CA",via LinkedIn,Full-time,False,"California, United States",2023-12-31 15:00:46,False,True,United States,year,271526.5,TikTok,"['sql', 'python', 'r', 'express']","{'programming': ['sql', 'python', 'r'], 'webfr...",12
421728,Data Analyst,Data Analyst - Operations,"Los Angeles, CA",via Indeed,Full-time,False,"California, United States",2023-12-31 16:00:07,False,True,United States,year,72750.0,Wilshire Law Firm Plc,"['sql', 'power bi', 'unity']","{'analyst_tools': ['power bi'], 'other': ['uni...",12
313161,Data Scientist,Data Scientist - Security Clearance Required,"Newport News, VA",via IT JobServe,Full-time,False,Georgia,2023-12-31 17:31:57,False,False,United States,year,114062.5,Leidos,"['python', 'r', 'sql', 'pandas', 'numpy']","{'libraries': ['pandas', 'numpy'], 'programmin...",12
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12

In [28]:
df1.describe()

                     job_posted_date  salary_year_avg  job_posted_month
count                          22003     22003.000000      22003.000000
mean   2023-06-13 01:01:01.813889024    123286.274072          5.886288
min              2023-01-01 00:02:56     15000.000000          1.000000
25%       2023-03-17 14:04:49.500000     90000.000000          3.000000
50%              2023-06-11 09:03:27    115000.000000          6.000000
75%              2023-08-26 00:41:15    150000.000000          8.000000
max              2023-12-31 23:40:32    960000.000000         12.000000
std                              NaN     48312.449482          3.296650

In [29]:
df1.count()

job_title_short          22003
job_title                22003
job_location             21723
job_via                  22003
job_schedule_type        21987
job_work_from_home       22003
search_location          22003
job_posted_date          22003
job_no_degree_mention    22003
job_health_insurance     22003
job_country              22003
salary_rate              22003
salary_year_avg          22003
company_name             22003
job_skills               20170
job_type_skills          20170
job_posted_month         22003
dtype: int64

In [32]:
df1['salary_year_avg'].median()

np.float64(115000.0)

In [36]:
min_salary = df1['salary_year_avg'].idxmin()

In [38]:
df1.iloc[min_salary]

IndexError: single positional indexer is out-of-bounds

In [39]:
df1['job_title_short'].unique()

array(['Data Scientist', 'Data Engineer', 'Business Analyst',
       'Data Analyst', 'Senior Data Engineer', 'Senior Data Scientist',
       'Senior Data Analyst', 'Software Engineer',
       'Machine Learning Engineer', 'Cloud Engineer'], dtype=object)

In [40]:
df1['job_title_short'].value_counts()

job_title_short
Data Scientist               5922
Data Analyst                 5451
Data Engineer                4500
Senior Data Scientist        1690
Senior Data Engineer         1591
Senior Data Analyst          1131
Business Analyst              610
Machine Learning Engineer     576
Software Engineer             467
Cloud Engineer                 65
Name: count, dtype: int64

In [41]:
df1.groupby('job_title_short')['salary_year_avg'].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [47]:
df1.groupby('job_title_short')['salary_year_avg'].agg(['min' , 'max' , 'median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0